version: '3.1'

volumes:
  pg_tg_demo_db:

services:
  tg_demo_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=tg_demo
    volumes:
      - pg_tg_demo_db:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"